services:
  fiap-estoque-postgres:
    image: postgres:16
    container_name: fiap-estoque-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata_estoque:/var/lib/postgresql/data

  fiap-estoque-service:
    build: .
    container_name: fiap-estoque-service
    depends_on:
      - fiap-estoque-postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://fiap-estoque-postgres:5432/stockdb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HTTP_PORT: 8080
    ports:
      - "8082:8080"

volumes:
  pgdata_estoque: